version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: condhub-ui
    container_name: condhub-ui
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules/
    ports:
      - "9000:9000"
    command: bash -c "chmod +x bash.sh && ./bash.sh"